### ISSUE TITLE
运行不了哇，可以看下我的问题吗

### ISSUE THREAD

**Issue by cuncun-edg** [XYZliang/AutoZFBXiaoYuanFangYiSign#11]

**Comment by XYZliang** [comment]
发报错截图

**Comment by cuncun-edg** [comment]
> 发报错截图

![image](https://user-images.githubusercontent.com/77426305/135720875-757adff2-504b-4e3c-93d5-02420a694490.png)
之前就是这里一直报错 我删除仓库 重新复刻就完事了，但是之前的错误一直没弄明白，谢谢回复
