### ISSUE TITLE
腾讯云函数报错

### ISSUE THREAD

**Issue by cuncun-edg** [XYZliang/AutoZFBXiaoYuanFangYiSign#32]
![image](https://user-images.githubusercontent.com/77426305/149442725-b2f1026b-7463-4b3d-aa4b-5e0a61fecbc4.png)

**Comment by cuncun-edg** [comment]
抱歉我解决了 配置文件修改为SignConfig.cfg 可就觉此错误

**Comment by XYZliang** [comment]
对的，名字搞错了
