### ISSUE TITLE
腾讯云调用函数失败

### ISSUE THREAD

**Issue by pokewin** [XYZliang/AutoZFBXiaoYuanFangYiSign#33]
![image](https://user-images.githubusercontent.com/76251863/149443332-da3cceb1-94fa-4cfc-a0db-13eea2bbc7c0.png)
![image](https://user-images.githubusercontent.com/76251863/149443329-3d751907-21bb-4a15-8470-448224ceaf6a.png)
![image](https://user-images.githubusercontent.com/76251863/149443336-9049959e-8a4a-4d1f-85dd-1b6c4beff9d6.png)

**Comment by cuncun-edg** [comment]
> 这是没有成功吧，啥原因呀？

配置文件修改为SignConfig.cfg

**Comment by XYZliang** [comment]
提示的很清楚哈，重命名为SignConfig.cfg

**Comment by pokewin** [comment]
OK解决了 谢谢哈

**Comment by XYZliang** [comment]
不客气
