### ISSUE TITLE
获取前一日定位，运行结果地址却没有与前一日的地址相同

### ISSUE THREAD

**Issue by cuncun-edg** [XYZliang/AutoZFBXiaoYuanFangYiSign#34]
![image](https://user-images.githubusercontent.com/77426305/149446084-7630b56e-9173-4c3f-9a1c-8de4263b5879.png)
![image](https://user-images.githubusercontent.com/77426305/149446154-0af3103e-fe14-4cf8-85a1-80bca1bd0f46.png)

**Comment by XYZliang** [comment]
应该是 #31 的问题，正在修复

**Comment by XYZliang** [comment]
新版本已修复
