### ISSUE TITLE
打卡地址问题

### ISSUE THREAD

**Issue by dotponder** [XYZliang/AutoZFBXiaoYuanFangYiSign#36]
今天查看了一下打卡记录，发现地址变化有点大，如图1所示。
![Screenshot_20220119_020154_com eg android AlipayG](https://user-images.githubusercontent.com/60877940/149993138-dce70e48-2baf-4535-94fc-ae9390dbeb1f.png)
图1 支付宝打卡显示地址
而腾讯云函数的配置文件如图2
![image](https://user-images.githubusercontent.com/60877940/149993265-ffcd6c22-5545-4ec4-942d-e737269c616c.png)
图2 配置文件截图

**Comment by dotponder** [comment]
已经提交了pull request，请查看

**Comment by XYZliang** [comment]
应该是 #31 的问题，正在修复

**Comment by XYZliang** [comment]
> 已经提交了pull request，请查看

包含你自己的个人隐私信息哈

**Comment by dotponder** [comment]
> > 已经提交了pull request，请查看
> 
> 包含你自己的个人隐私信息哈

好家伙，我都没发现，谢谢提醒
