### ISSUE TITLE
腾讯云函数测试运行失败

### ISSUE THREAD

**Issue by wqn200133** [XYZliang/AutoZFBXiaoYuanFangYiSign#39]
日志如下，都是按教程编辑的
日志:

START RequestId: ace22e28-5253-4d81-83a4-390980e7d39d

配置文件和配置模板文件均已丢失，请从github从新获取

项目出错，请查看程序输出

Init Report RequestId: ace22e28-5253-4d81-83a4-390980e7d39d Coldstart: 757ms (PullCode: 7ms InitRuntime: 7ms InitFunction: 743ms) Memory: 128MB MemUsage: 0.25MB

ERROR RequestId: ace22e28-5253-4d81-83a4-390980e7d39d Result: {"errorCode": -1, "errorMessage": "", "statusCode": 443}

END RequestId: ace22e28-5253-4d81-83a4-390980e7d39d

Report RequestId: ace22e28-5253-4d81-83a4-390980e7d39d Duration: 0ms Memory: 128MB MemUsage: 0.25MB

START RequestId:ace22e28-5253-4d81-83a4-390980e7d39d

ERROR RequestId:ace22e28-5253-4d81-83a4-390980e7d39d Result:{"errorCode":-1,"errorMessage":"UserCodeError","statusCode":443}

END RequestId:ace22e28-5253-4d81-83a4-390980e7d39d

Report RequestId:ace22e28-5253-4d81-83a4-390980e7d39d Duration:0ms Memory:128MB MemUsage:0.000000MB

**Comment by XYZliang** [comment]
配置文件重命名错了吧

**Comment by wqn200133** [comment]
> 配置文件重选错了吧
BigStudyConfig.cfg 啊~需要该哪里
![Uploading 1.png…]()
啊

**Comment by wqn200133** [comment]
BigStudyConfig.cfga&nbsp;







------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年2月5日(星期六) 晚上6:02
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [XYZliang/AutoZFBXiaoYuanFangYiSign] 腾讯云函数测试运行失败 (Issue #39)





 
配置文件重命名错了吧
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
