### ISSUE TITLE
小小的优化建议

### ISSUE THREAD

**Issue by Barry04** [XYZliang/AutoZFBXiaoYuanFangYiSign#4]
设置每一天几个时间段重复运行，体验有点不舒服，毕竟会发提示到微信。我建议可以通过获取log来判断今天是否已经打卡，已经打卡结束程序。还有多人签到打卡可以设置间隔一段随机的时间，更加真实。。。上述的功能我已经实现，并且已经修改在我本人的仓库。

**Comment by YeLei1998** [comment]
根据你提示，我fork了你的仓库，也修改了对应的代码，方糖每天9点半左右给我推送消息，说打卡成功，但是老师还是每天提醒我打卡，我是不是哪里出了问题，望回复，谢谢！

**Comment by Barry04** [comment]
你可以自己去支付宝的打卡记录里面看看，有没有当天打卡的记录。应该不存在这种情况，我看了你的仓库。。就是假如今天已经打卡成功了，你自己再去支付宝试试看还能不能打卡，如果可以就是有问题，不可以就是没有问题。要不就是你老师弄错了。这个我已经用了一个学期了，目前没有出现你所说的情况。

**Comment by YeLei1998** [comment]
hxd,它(方糖)每次说我打卡成功，然后日志和session都有更新，我去支付宝查看打卡记录就是没有，而且我在支付宝点签到还能签到，很郁闷啊

**Comment by Barry04** [comment]
那你fork原博主的再试试看

**Comment by XYZliang** [comment]
> 设置每一天几个时间段重复运行，体验有点不舒服，毕竟会发提示到微信。我建议可以通过获取log来判断今天是否已经打卡，已经打卡结束程序。还有多人签到打卡可以设置间隔一段随机的时间，更加真实。。。上述的功能我已经实现，并且已经修改在我本人的仓库。

哈哈哈，重复运行原意是怕签到偶尔失败，多次签到也没什么，消耗不了多少github资源。当然通过日志判断更好了，之前偷懒～可以提交一下pr～
