### ISSUE TITLE
腾讯云函数那个，还是我，刚刚不小心结束了，配置文件重命名是按照教程来的

### ISSUE THREAD

**Issue by wqn200133** [XYZliang/AutoZFBXiaoYuanFangYiSign#40]
BigStudyConfig.cfg 就是这个

**Comment by XYZliang** [comment]
截图看看

**Comment by XYZliang** [comment]
按步骤不会有错，肯定是拿弄错了

**Comment by wqn200133** [comment]
![1](https://user-images.githubusercontent.com/63901406/152641389-85266c89-b294-4223-b34f-16dcde5091c6.png)
![文件2](https://user-images.githubusercontent.com/63901406/152641392-cfd3b112-c0f9-4132-bd94-0526b75d338f.png)
![文件3](https://user-images.githubusercontent.com/63901406/152641393-6c6f0250-4ec0-447c-9bfd-03c10692bff4.png)

**Comment by wqn200133** [comment]
> 按步骤不会有错，肯定是拿弄错了

谢谢大佬，图发了

**Comment by wqn200133** [comment]
> 按步骤不会有错，肯定是拿弄错了

大佬你好，我成功了，发现是A方案第中重命名文件步骤应改为StudyConfig.cfg，非教程里面的BigStudyConfig.cfg~

**Comment by XYZliang** [comment]
是的，那个地方的描述我copy错了，一会我改一下
