### ISSUE TITLE
网页登录

### ISSUE THREAD

**Issue by lcqadmin** [XYZliang/AutoZFBXiaoYuanFangYiSign#42]
打卡网页登陆需要数字验证码，怎么打卡？作者有办法吗？

**Comment by XYZliang** [comment]
数字验证码??不需要使用验证码进行登录的，有个自动登陆的api，直接用它去登陆来获取账号cookie的，我的文档有写

**Comment by lcqadmin** [comment]
> 数字验证？？不需要验证进行登录的，自动登陆码的api，直接用它去登陆来获取文档记录cookie的，我的有写的

我们学校的和这个不一样，需要网页登陆，不知道如何登陆验证码，识别验证码成功率太低
