### ISSUE TITLE
Windows server 2012出现错误404：Not Found

### ISSUE THREAD

**Issue by Chen-913** [XYZliang/AutoZFBXiaoYuanFangYiSign#43]
![image](https://user-images.githubusercontent.com/72293244/155122828-d2bc37cd-b1f4-4513-a0ba-d56e210c0802.png)

# 错误描述
出现如上错误，运行的时候是没有问题的，也记录了log文件，显示已经签到了
但是后面运行就出现这样的错误了，我在本地的电脑调试好之后传到服务器上运行的，以为是服务器的缘故
于是我又在本地电脑运行了一次，结果也是这样的错误
20分钟后。。。大概是一顿饭的时间，我抱着侥幸的心理在本地电脑又运行了一次，结果又没问题了，请问是怎么回事
> 本人不是很懂python，就是clone下来改了报错的地方，成功跑起来了

![image](https://user-images.githubusercontent.com/72293244/155122903-e449d359-67a4-423e-97f0-87391c4491fd.png)

**Comment by XYZliang** [comment]
可能有几个原因：
1.你开了代理，这个代理出问题了，或者这个代理去了国外，国外ip被这个打卡的服务器屏蔽了，代理关了去
2.偶尔的网络波动错误，多试几次
3.随机生成的设备标识有问题，但是这个概率几乎为0，可以不考虑，其他人使用全部正常
4.你的服务器是否ip不在中国大陆？
5.一些莫名其妙的原因，你的ip被打卡服务器拉黑了，更换ip

**Comment by Chen-913** [comment]
没有开代理，估计是ip被封了

**Comment by 7ikun** [comment]
请问第11步这个文件在哪里呀？
