### ISSUE TITLE
腾讯云函数测试时，提示Unused variable 'res'

### ISSUE THREAD

**Issue by TherstFeng** [XYZliang/AutoZFBXiaoYuanFangYiSign#45]
腾讯云函数测试时，提在问题一栏提示Unused variable 'res'；不知道该如何解决，是我那一步出错了吗？
<img width="952" alt="Snipaste_2022-03-20_12-54-37" src="https://user-images.githubusercontent.com/39232323/159148865-a5c911b7-3523-4377-82d7-8191756a109e.png">
<img width="970" alt="Snipaste_2022-03-20_12-54-04" src="https://user-images.githubusercontent.com/39232323/159148874-8b04f3c5-448f-44cc-9d2f-23e74ad9da1e.png">

**Comment by TherstFeng** [comment]
@XYZliang 求大佬解答

**Comment by XYZliang** [comment]
警告而已，不影响正常运行
