### ISSUE TITLE
API失效

### ISSUE THREAD

**Issue by DZZ520** [XYZliang/AutoZFBXiaoYuanFangYiSign#51]
![image](https://user-images.githubusercontent.com/35104549/167054057-ed00febb-222a-463d-993c-a640c505f7e2.png)

![940078b5356e49eb310682d6be5bb21](https://user-images.githubusercontent.com/35104549/167054082-3086e591-fedf-45ef-939c-91b5e4b36d61.jpg)
调用API 的网页404失效，有解决方法吗？

**Comment by XYZliang** [comment]
见#53
