### ISSUE TITLE
测试成功了，但是调用失败

### ISSUE THREAD

**Issue by pokewin** [XYZliang/AutoZFBXiaoYuanFangYiSign#56]
![image](https://user-images.githubusercontent.com/76251863/167523323-f4cab0e7-79e8-45be-9e2a-6c17fdd15790.png)
![image](https://user-images.githubusercontent.com/76251863/167523357-d7d1ff81-9fff-412e-afc1-63873479419c.png)
![image](https://user-images.githubusercontent.com/76251863/167523385-e47d7d0b-fdc7-455a-9f17-2ff281d65e4d.png)
![image](https://user-images.githubusercontent.com/76251863/167523395-8ebcabae-f89a-4543-b0c7-16fb5659741f.png)

**Comment by pokewin** [comment]
可以帮忙看看嘛

**Comment by sugar1777** [comment]
别部署腾讯云函数了，那玩意五月底可能就要收费了

**Comment by pokewin** [comment]
> 别部署腾讯云函数了，那玩意五月底可能就要收费了

ok

**Comment by XYZliang** [comment]
见#53
