### ISSUE TITLE
打不了卡啦

### ISSUE THREAD

**Issue by jiangjiangla** [XYZliang/AutoZFBXiaoYuanFangYiSign#69]
是不是系统更新了啊

**Comment by Darkoutput** [comment]
大佬分享下你之前制作的快捷指令呗

**Comment by XYZliang** [comment]
见https://github.com/XYZliang/AutoZFBXiaoYuanFangYiSign/issues/71#issuecomment-1186825546

**Comment by XYZliang** [comment]
见https://github.com/XYZliang/AutoZFBXiaoYuanFangYiSign/issues/71#issuecomment-1186825546
