### ISSUE TITLE
登录失败，查看log文件找到一个网址，登录显示如下

### ISSUE THREAD

**Issue by Man1412** [XYZliang/AutoZFBXiaoYuanFangYiSign#70]
![QQ截图20220711165159](https://user-images.githubusercontent.com/91924151/178226248-7d908453-dda2-4284-b7da-c01f94ecfc95.png)
![QQ截图20220711165159](https://user-images.githubusercontent.com/91924151/178226248-7d908453-dda2-4284-b7da-c01f94ecfc95.png)

**Comment by Man1412** [comment]
![QQ截图20220711165512](https://user-images.githubusercontent.com/91924151/178226918-13335b76-e617-4304-91f7-61c73a7a81da.png)
这个好像没法解决吧

**Comment by Man1412** [comment]
[2022-07-13.zip](https://github.com/XYZliang/AutoZFBXiaoYuanFangYiSign/files/9097692/2022-07-13.zip)

**Comment by Chordp** [comment]
网站接口无了,建议支付宝抓包拿cookie 签到

**Comment by XYZliang** [comment]
见https://github.com/XYZliang/AutoZFBXiaoYuanFangYiSign/issues/71#issuecomment-1186825546
