### ISSUE TITLE
寻求帮助，在线吗

### ISSUE THREAD

**Issue by zhangyiyuan25** [XYZliang/AutoZFBXiaoYuanFangYiSign#9]
我有一个阿里云服务器，代码跑不起来，报错，我python，pip什么环境都安装好了，运行报错，要不加一下qq，或者远程一下，有没有简单的代码，我也不懂python，直接上传服务器自动运行，简单一点，就是

**Comment by XYZliang** [comment]
直接发报错截图

**Comment by pokewin** [comment]
在学号那里报错（NameError: name 'T2020****' is not defined）咋整呀

**Comment by XYZliang** [comment]
完整的报错全部发上来

**Comment by pokewin** [comment]
就是这样的
这是我配的，你看看有啥问题





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "XYZliang/AutoZFBXiaoYuanFangYiSign"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月9日(星期天) 晚上6:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [XYZliang/AutoZFBXiaoYuanFangYiSign] 寻求帮助，在线吗 (#9)





 
完整的报错全部发上来
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by pokewin** [comment]
![image](https://user-images.githubusercontent.com/76251863/148780335-490a3de2-abbd-45f6-8cb2-c4103122fc88.png)
![image](https://user-images.githubusercontent.com/76251863/148780338-5eab2a8b-94c0-429a-8101-d17156e13b2f.png)
![image](https://user-images.githubusercontent.com/76251863/148780342-6529192f-dea2-49c4-809e-22a468b72c06.png)

**Comment by Barry04** [comment]
可能是学号的问题，吧T去了试试看

**Comment by XYZliang** [comment]
这确实是个潜在bug，我没有考虑到学号还会包含字母。
解决方法也很简单，只需要学号那用引号括起来：
`yourID = 'T2020208149'`

**Comment by pokewin** [comment]
好的好的，谢谢啦

**Comment by XYZliang** [comment]
新版已经完全解决了这个问题，也无需注意添加引号
